# Generated by Django 3.1.4 on 2020-12-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arcade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
    ]
