# Generated by Django 3.1.4 on 2020-12-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arcade', '0002_remove_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
